### PR TITLE
dependency updates with test run successfully

### PR DESCRIPTION
**Pull request by ravihara**
Dependency updates including devDependencies.

### CODE REVIEW

**Comment by cressie176** [comment]
Thanks. Looks like the lru-cache had a major version bump, but it was just because they dropped support for pre-10 versions of node. The build failure is because mocha requires 10 or higher too.

I'll have a think and see if I'm comfortable with loosing node v8 support. It's pretty old now but I suspect some people are still using it.

**Comment by ravihara** [comment]
> Thanks. Looks like the lru-cache had a major version bump, but it was just because they dropped support for pre-10 versions of node. The build failure is because mocha requires 10 or higher too.
> 
> I'll have a think and see if I'm comfortable with loosing node v8 support. It's pretty old now but I suspect some people are still using it.

Yes.. most cloud service providers also dropped support for Node V8.x. You are right.. it's mainly mocha requirement as far as travis-ci build failure for node-8 build is concerned.

**Comment by cressie176** [comment]
Seems like the tail wagging the dog - a test dependency dictating what version of node the main library supports. There's no need to upgrade to latest mocha other than to get rid of some dependency warnings. I think leave things as is for now - Node 8 is only out of support by ~8 months.

**Comment by ravihara** [comment]
> Seems like the tail wagging the dog - a test dependency dictating what version of node the main library supports. There's no need to upgrade to latest mocha other than to get rid of some dependency warnings. I think leave things as is for now - Node 8 is only out of support by ~8 months.

I'm not sure if we need to blame Mocha for this. Feature and vulnerability updates are more common in Node ecosystem. It's rather advisable for the dependent projects to update their dependencies and code accordingly. Anyway, there is no hard push to merge this but, I don't see a strong reason to continue with Node 8.

**Comment by cressie176** [comment]
We disagree. Regarding your three points...

1. I'm not sure if we need to blame Mocha for this
1. It's rather advisable for the dependent projects to update their dependencies and code accordingly
1. I don't see a strong reason to continue with Node 8.

Blame is too harsh a word, especially when we're talking about open source and people freely sharing the product of their labour. However, mocha (and another of popular and well established modules) are responsible for a disproportionately high number of `npm audit` vulnerabilities because of the libraries they depend on. Because mocha is a test dependency, these vulnerabilities are often benign, but still clog up the audit report, making it more difficult to spot genuine vulnerabilities, or creating otherwise unnecessary work to update them. This work is made harder if the user has to also bump node versions. In our environment we manage 100s of node applications, so this type of unnecessary work can be extremely wasteful and disruptive.

`npm audit` and even `nsp` are relatively recent developments compared to how long mocha has been around, so I absolutely do not blame it for getting into the current state (especially since Rascal has similar issues because of its dependency on lodash). However it is part of good module to minimise maintenance requirements. This can be done by depending on as few libraries as possible and avoiding/replacing libraries that have historically had a high number of vulnerabilities or unnecessary breaking changes. 

Since good module design is the responsibility of module authors, and good module design should consider maintenance, the authors of mocha are accountable for the dependencies they select, at least to the extent that any popular open source authors are (which I accept you could argue is 0). Maybe the best way of looking at it is, to the extent that the authors hold themselves accountable.

I also take this responsibility seriously, which is why I won't assume the users of Rascal have no strong reason to upgrade from node 8, even though it may be out of LTS.

**Comment by ravihara** [comment]
> We disagree. Regarding your three points...
> 
>     1. I'm not sure if we need to blame Mocha for this
> 
>     2. It's rather advisable for the dependent projects to update their dependencies and code accordingly
> 
>     3. I don't see a strong reason to continue with Node 8.
> 
> 
> Blame is too harsh a word, especially when we're talking about open source and people freely sharing the product of their labour. However, mocha (and other popular and well established modules) are responsible for a disproportionately high number of `npm audit` vulnerabilities because of the libraries they depend on. Because mocha is a test dependency, these vulnerabilities are often benign, but still clog up the audit report, making it more difficult to spot genuine vulnerabilities, or creating otherwise unnecessary work to update them. This work is made harder if the user has to also bump node versions. In our environment we manage 100s of node applications, so this type of unnecessary work can be extremely wasteful and disruptive.
> 
> `npm audit` and even `nsp` are relatively recent developments compared to how long mocha has been around, so I absolutely do not blame it for getting into the current state (especially since Rascal has similar issues because of its dependency on lodash). However it is part of good module design to minimise maintenance requirements. This can be done by depending on as few libraries as possible and avoiding/replacing libraries that have historically had a high number of vulnerabilities or unnecessary breaking changes.
> 
> Since good module design is the responsibility of module authors, and good module design should consider maintenance, the authors of mocha are accountable for the dependencies they select, at least to the extent that any popular open source authors are (which you could argue is 0). Maybe the best way of looking at it is, to the extent that the authors hold themselves accountable.
> 
> I take this responsibility seriously, which is why I won't assume the users of Rascal have no strong reason to upgrade from node 8, even though it may be out of LTS.

Following on the lines on what you said about Mocha, open source projects if need to take care of these dependency upgrade issues, might need to switch to alternatives which support maintainability and support goals of the project in hand. So, one option would be look for alternatives to Mocha itself (even though that could be quite an effort to migrate tests).

While I'm completely fine, if you ignore this merge request for dependency updates, I as a user of this library too feel that, it should be sufficient to follow and support LTS versions of Node.js. Otherwise, it is also not very uncommon to maintain two major versions in parallel, especially if one feels that, user adoption of this library will be drastically affected if we stop the support for old LTS node versions.

**Comment by cressie176** [comment]
Hi @ravihara,

> So, one option would be look for alternatives to Mocha itself

I've been thinking along the same lines, however I'm not particularly fond of any test library (I'm familiar with Jest, Tape, Jasmine and qunit. Right now the option which is least effort and does no harm, is to keep mocha as is.

Re your Sync commit - https://github.com/guidesmiths/rascal/issues/98 and https://support.snyk.io/hc/en-us/articles/360000897937-Why-is-Snyk-added-into-my-production-dependencies-

I'm going to close this PR, as I bumped the dependencies I'm comfortable with in the last release. Thanks for your time putting it together though, and for the discussion

**Comment by ravihara** [comment]
> Hi @ravihara,
> 
> > So, one option would be look for alternatives to Mocha itself
> 
> I've been thinking along the same lines, however I'm not particularly fond of any test library (I'm familiar with Jest, Tape, Jasmine and qunit. Right now the option which is least effort and does no harm, is to keep mocha as is.
> 
> Re your Sync commit - #98 and https://support.snyk.io/hc/en-us/articles/360000897937-Why-is-Snyk-added-into-my-production-dependencies-
> 
> I'm going to close this PR, as I bumped the dependencies I'm comfortable with in the last release. Thanks for your time putting it together though, and for the discussion

Cool! Sounds good. I understand the value of time you guys (or anyone contributing to a FOSS project) are putting in, apart from your other work. Hope that these dependency anomalies are better handled by Node.js community in general.

**Pull request closed without merging**
